### ISSUE TITLE
error: RNGestureHandlerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage

### ISSUE THREAD

**Issue by ZeroCho** [kmagiera/react-native-gesture-handler#11]
I followed all instructions in `README.md` including altering `MainActivity.java` and linking.

Still following error happens. Is this package not compatible with Android + RN 0.46?

```
C:\Users\zerocho\WebstormProjects\puzzle\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerPackage.java:24: error: RNGestureHandlerPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNGestureHandlerPackage implements ReactPackage {
       ^
Note: C:\Users\zerocho\WebstormProjects\puzzle\node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

BUILD FAILED

Total time: 15.779 secs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gesture-handler:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by kmagiera** [comment]
@ZeroCho we aim for a compatibility with 0.47+. Apparently due to this very unfortunate braking change introduced in 0.47 https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
Other than that there are no other compatibility issues except from the fact that a few improvements to Animated library has been added to 0.47 that this library does not directly rely on but if you plan on using nativeDriver along with it they may be useful.

Apparently there is nothing I can do about the method that has been removed in 0.47. I can only recommend upgrading to 0.47 or creating a fork that would add that method back – the relevant commit is here https://github.com/kmagiera/react-native-gesture-handler/commit/fd9efed14cb5dacdf89ef800b2b83ba56bfed0bb#diff-744a92e1bc2e20dc72b2b8b062df7618

I don't think that the surface area between this library and RN will significantly change with the next releases so the fork shouldn't require a lot of maintenance besides just doing upstream merges from time to time.

Sorry about your trouble

**Comment by ZeroCho** [comment]
@kmagiera Thank you for answer! I'll have to wait until most packages support RN47. I guess most packages other than this one have compatibility issues with RN47, due to `createJSModule` 😢
