### ISSUE TITLE
Are dragable rows of list possible?

### ISSUE THREAD

**Issue by danielang** [kmagiera/react-native-gesture-handler#111]
Hello 🙂 

Thank you for this great library!
I've a question: Is it possible to move a clone of a row?

I've the following scenario: My view renders cards with an image and the headline of an article.
I want to achive that when I longpress them, a clone of the pressed card can be dragged to the bottom of the screen, where the user can select how the article will be archived (with/without images).

Thank you!

**Comment by kmagiera** [comment]
Hey @danielang! Thanks for reaching out

This should definitely be possible. You should use LongPressHandler for that and when it turns to "ACTIVE" then update row params so that these are positioned absolutely. You will also need to use PanHandler registered for the same view to help you track movements, but only enable the tracking when longpress handler is in the ACTIVE state
