### ISSUE TITLE
Gesture Handlers stop responding when swapped.

### ISSUE THREAD

**Issue by rozele** [kmagiera/react-native-gesture-handler#18]
I have a simple demo here:
https://snack.expo.io/Bkr5lme9W

Basically, you can use 1-finger panning to modify the pitch and yaw of the look-at matrix, and 2-finger panning in the y-axis to move the origin forward or backward in the direction of the "gaze". 

I added a button to switch from 2-finger panning to pinch to move forward or backward, and when you hit this button, it seems to break the gesture handling.

Here's a video repro as well: https://youtu.be/xTC6Nh6j8NE

This seems to repro on either iOS or Android.

**Comment by kmagiera** [comment]
Thanks @rozele for reporting. Will look into this soon

**Comment by kmagiera** [comment]
So the issue was that we werend handling GH lifecycle propertly as it was bound to the underlying native view. When you swap out one of the handlers then the top one stays the same and the underlying view gets recreated. This should result in handler sticking around but just updating its target view. But instead we were dropping all the handlers when the view got unmounted.

To fix this I had to change the bridge API by adding `attachGestureHandler` as well as changing the contract of `createGestureHandler` or `updateGestureHandler` methods which now no longer take viewID as an argument. Also `dropGestureHandler` method replaced `dropGestureHandlersForView` to allow for deleting handlers selectively.

Changes are not yet merged and you can play with them here: https://github.com/kmagiera/react-native-gesture-handler/tree/bridge_api_change

Thanks again for your feedback @rozele

**Comment by kmagiera** [comment]
Fixed in #24 
Thanks again for reporting
