### ISSUE TITLE
Swipeable Hangs 

### ISSUE THREAD

**Issue by brennanerbz** [kmagiera/react-native-gesture-handler#269]
When swiping a row in the Swipeable example, the row hangs for fraction of the second then finishes the animation. Nothing is broken, but it doesn't feel like the native experience. Is this just a limitation with React Native?

**Comment by AbdallaMohamed** [comment]
It needs to pass over the bridge since the logic that determines whether the row will be open or closed is written in JS. `react-native-reanimated` mitigates that by making everything declarative. Would be pretty awesome if a proper swipeable component was built with it and shared in a repo.

**Comment by osdnk** [comment]
@AbdallaMohamed is right. If JS is not busy it works quite fine, but it's a great problem in fact. I wish to build it fully declaratively some day and export it via `reanimated`

**Comment by samu** [comment]
@osdnk @AbdallaMohamed @brennanerbz  I believe this is due to the `velocityX` value being divided by `friction`, for example [here](
https://github.com/kmagiera/react-native-gesture-handler/blob/0f6768cd1fa8cf095fc62cfe0e8f9d9fc9e6a02f/Swipeable.js#L179) (there are two other occasions where this is done).

The laggy effect which is reported here is not due to the bridge being too slow - it's the human gesture that is being interrupted and then slowed down.

Here's how react-nativgation does it: [link](
https://github.com/react-navigation/react-navigation-stack/blob/7d13e7b7130b91a5dd3c5c8ee76ece15d137cc30/src/views/StackView/StackViewLayout.js#L572). As you can see, the velocity that is faster wins (if the human gesture is faster, the animation should be completed with that velocity, otherwise, it will look as if the animation lags).

I did a quick test if my claims are correct by monkeypatching inside node_modules (removed the ` / friction` parts). If i then run on a real device, the lag is gone.
