### ISSUE TITLE
"PanGestureHandler" not working with "ImageBackground"

### ISSUE THREAD

**Issue by khat33b** [kmagiera/react-native-gesture-handler#282]
When `PanGestureHandler` is used with `ImageBackground`, the methods `onGestureEvent` and `onHandlerStateChange` do not trigger.

This is an example code:
```
import React, { Component } from 'react';
import {
  View,
  ImageBackground,
} from 'react-native';
import { State, PanGestureHandler } from 'react-native-gesture-handler';

export default class Test extends Component {

  _onGestureEvent = event => {
    console.log(event);
  };

  _onHandlerStateChange = event => {
    console.log(event);
  };

  render(){
      return (
        <PanGestureHandler
          onGestureEvent={this._onGestureEvent}
          onHandlerStateChange={this._onHandlerStateChange}>
            <ImageBackground style={{width: '100%', height: '100%'}} source={{uri: 'http://images.cinedigm.com/CEG10022532_312x472_0.jpg'}}/>
        </PanGestureHandler>
      );
    }
}
```

**Comment by osdnk** [comment]
Hi, thank you for this issue. 
Well, I'm afraid it should not work, because Gesture Handler could be attached only to animated views. Please wrap it ion `Animated.View` of use `const AninamatedImageBackground = Animated.createAnimatedComponent(ImageBackground)` in  order to handle your case. Please mind that the second solution is not officially supported
