### ISSUE TITLE
Duplicate module name: react-native

### ISSUE THREAD

**Issue by JeffGuKang** [kmagiera/react-native-gesture-handler#404]
The podspec cause the problem as below when I try `react-native start` after pod install. 

```
Loading dependency graph...(node:73522) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
```

React is deprecated in Cocoapod. 

RNGestureHandler.podspec

```
s.dependency "React" 
```

And it makes others confused even they are using `react-native link` instead of cocoapod.

**Comment by chrisjasp** [comment]
@angly-cat I'm not sure I fully understand your question but I do not have a reference to React in my Podfile if that is what you are asking.

**Comment by JeffGuKang** [comment]
@angly-cat @chrisjasp  It looks same case of this issue. https://github.com/AlexanderZaytsev/react-native-i18n/issues/170

IT can be solved to config project's podfile. [Official](https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies).

**Comment by angly-cat** [comment]
My point is that if you're linking a React Native library through Podfile, then you're basically forced to include React Native/yoga to your project through Podfile too. And after that you're forced to include all other React Native libraries through Podfile as well.

I may be wrong in something, but before I switched from cocoapods to including React Native libraries manually, it was very painful for me to upgrade React Native, because there're usually many pods-related bugs in React Native. And since React Native developers don't use cocoapods, it's more likely to be broken comparing to manual linking. Just sharing my experience.

**Comment by Balake** [comment]
@JeffGuKang I had the same issue and it was solved by adding React/Yoga to my podfile like @lebedev suggested: 
```
pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
```
