### ISSUE TITLE
Receiving simultaneous ScrollView and GestureHandler events

### ISSUE THREAD

**Issue by naftalibeder** [kmagiera/react-native-gesture-handler#492]
Is it possible to receive events for a handler, e.g. `PanGestureHandler`, and a `ScrollView` at the same time? I’m finding that a `ScrollView` fully consumes a touch event, even with `simultaneousHandlers` set, so that a gesture handler that contains the `ScrollView` never receives the touch as long as the `ScrollView` is enabled.

**Comment by naftalibeder** [comment]
Answer: Wrapping the `ScrollView` in a `NativeViewGestureHandler`, with both gesture handlers pointing to each other's refs in the `simultaneousHandlers` prop, works perfectly.

**Comment by damikdk** [comment]
There is no documentation about `NativeViewGestureHandler` on official site, but the [only mention of it](https://kmagiera.github.io/react-native-gesture-handler/docs/about-handlers.html#using-native-components) says that you can use `FlatList` from `react-native-gesture-handler` with `simultaneousHandlers` instead of wrapping it inside `NativeViewGestureHandler`.

**But you cannot**
```
import { FlatList, PanGestureHandler } from 'react-native-gesture-handler';

// This handler will only fire if FlatList does not detect scroll
<PanGestureHandler
  ref={panRef}
  simultaneousHandlers={listRef}
>
  <FlatList
    ref={listRef}
    simultaneousHandlers={panRef}
    ...
  />
</PanGestureHandler>
```

So you still should use `FlatList`**ONLY** from `react-native` and wrap it in `NativeViewGestureHandler`:

```
import { FlatList } from 'react-native';
import { PanGestureHandler, NativeViewGestureHandler } from 'react-native-gesture-handler';

<PanGestureHandler
  ref={panRef}
  simultaneousHandlers={listRef}
>
  <NativeViewGestureHandler
    ref={listRef}
    simultaneousHandlers={panRef}
  />
    <FlatList/>
  </NativeViewGestureHandler>
</PanGestureHandler>
```

There is no `FlatList` in [current documentation](https://github.com/kmagiera/react-native-gesture-handler/blob/ff74e0edadd62518b45d85f251f527307457ab9e/docs/handlers.md) from this repo. But it was added in [this](https://github.com/kmagiera/react-native-gesture-handler/pull/559/files#diff-f597d014bd77ac39cda56c6879665d25R20) PR. IDK

**Comment by yzalvov** [comment]
@damikdk thanks, your research helped me. 

I'd add one caveat though. For anybody planning to use `Animated.event` for `PanGestureHandler`  `onHandlerStateChange` for example. In that case one must wrap a `NativeViewGestureHandler` inside an `Animated.View`. Otherwise the app will be failing with an error `Nesting touch handlers with native animated driver is not supported yet`. [Credits](https://github.com/software-mansion/react-native-gesture-handler/issues/71#issuecomment-351361705).

Just in case, here's a full example:
```js
const ScrollView = styled(Animated.ScrollView).attrs({scrollEventThrottle: 16})`
  padding-bottom: 40px;
`


const Container = React.forwardRef((props, ref) => {
  const handlerRef = useRef()
  const { scrollRef, onScroll, onHandlerStateChange, children } = props
  
return <PanGestureHandler {...{onHandlerStateChange}} simultaneousHandlers={handlerRef}>

    <Animated.View>

      <NativeViewGestureHandler ref={handlerRef}>
        <ScrollView ref={scrollRef} {...{onScroll}}>
          {children}
        </ScrollView>
      </NativeViewGestureHandler>

    </Animated.View>

  </PanGestureHandler>
})

**Comment by kulikalov** [comment]
I use `react-native-gesture-handler@1.6.1`. It seems neither of the suggested solutions work. I've tried all kinds of `simultaneousHandlers` combinations, `ScrollView`s from `react-native-gesture-handler` and from `react-native` etc.

Here:

```
class List extends PureComponent<Props> {
  panRef
  listRef
  render () {
    const { children } = this.props
    return (
      <View style={styles.container}>
        <PanGestureHandler
          onGestureEvent={() => console.log('onGestureEvent')}
          ref={ref => (this.panRef = ref)}
          simultaneousHandlers={this.listRef}
        >
          <NativeViewGestureHandler
            ref={ref => (this.listRef = ref)}
            simultaneousHandlers={this.panRef}
          >
            <ScrollView
              // scrollEnabled={false}
              style={styles.foodListScroll}
            >
              {children}
            </ScrollView>
          </NativeViewGestureHandler>
        </PanGestureHandler>
      </View>
    )
  }
}
```

`PanGestureHandler` fires `onGestureEvent` only when the `ScrollView` is disabled with `scrollEnabled={false}`.

**Comment by kulikalov** [comment]
@damikdk @yzalvov  could you take a look?

**Comment by ehsan6sha** [comment]
This combination for me worked for Reanimated.ScrollView.

PanGestureHandler (simref to nativeView) > Reanimated.View > NativeViewGestureHandler(simref to Pan) > Reanimated.ScrollView (RecyclerListView)

**Comment by ahmetkuslular** [comment]
@ehsan6sha can you post sample code?

**Comment by ehsan6sha** [comment]
> @ehsan6sha can you post sample code?

You can checkout the code here:
https://github.com/functionland/photos
in file
components/SingleMedia.tsx

line 437 untill 493

**Comment by haibert** [comment]
@ehsan6sha @yzalvov @damiansf 
Do you guys know if is possible to use the logic discussed in this thread to achieve the results shown in this gif? This is how Tiktok's user profile works. I have tried so many different ways to achieve the results, but it is very difficult to lock the inner list until the header is hidden and pass the velocity information to the flat list so it continues to scroll. 

https://user-images.githubusercontent.com/31780749/133121423-9805fe2c-464e-40ff-a844-0e6dbf8a38d7.gif

**Comment by jose31canizar** [comment]
> @ehsan6sha @yzalvov @damiansf Do you guys know if is possible to use the logic discussed in this thread to achieve the results shown in this gif? This is how Tiktok's user profile works. I have tried so many different ways to achieve the results, but it is very difficult to lock the inner list until the header is hidden and pass the velocity information to the flat list so it continues to scroll.
> 
> ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/31780749/134820610-568b318e-334d-4cdd-9c3c-b15d03665c3c.gif)

I actually recently figured out how to do this and I'm surprised how complicated it actually is. I might make a video on how to implement it and/or release a library that enables you to do exactly what you're showing on your gif. The idea is to have a pan gesture handler wrapping your  native view that wraps your scrollview (in my case I use an animated VirtualizedList since FlatList has issues with gesture handlers). I did not need to pass velocity info in the end, but I track a lot of state in shared values (whether you are scrolling the scrollview or the header, the scrollview's content offset, at what content offset did you start scrolling back up to show the header, etc.).

**Comment by ChrisYohann** [comment]
> > @ehsan6sha @yzalvov @damiansf Do you guys know if is possible to use the logic discussed in this thread to achieve the results shown in this gif? This is how Tiktok's user profile works. I have tried so many different ways to achieve the results, but it is very difficult to lock the inner list until the header is hidden and pass the velocity information to the flat list so it continues to scroll.
> > ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/31780749/134820610-568b318e-334d-4cdd-9c3c-b15d03665c3c.gif)
> >       
> >         [
> >           
> >         ](https://user-images.githubusercontent.com/31780749/134820610-568b318e-334d-4cdd-9c3c-b15d03665c3c.gif)
> >         
> >             ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/31780749/134820610-568b318e-334d-4cdd-9c3c-b15d03665c3c.gif)
> >           
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/31780749/134820610-568b318e-334d-4cdd-9c3c-b15d03665c3c.gif)
> 
> I actually recently figured out how to do this and I'm surprised how complicated it actually is. I might make a video on how to implement it and/or release a library that enables you to do exactly what you're showing on your gif. The idea is to have a pan gesture handler wrapping your native view that wraps your scrollview (in my case I use an animated VirtualizedList since FlatList has issues with gesture handlers). I did not need to pass velocity info in the end, but I track a lot of state in shared values (whether you are scrolling the scrollview or the header, the scrollview's content offset, at what content offset did you start scrolling back up to show the header, etc.).

Hi @jose31canizar I'm struggling for days to achieve exactly this (Instagram has the same behavior on their profile page). Could you share more information please ? At the beginning each tab was a react-native `ScrollView` which I positioned absolutely, and I played with `contentOffset` and `contentInset` properties to make the content of each tab starts below the "static" data. It was working fine, but then I realized that all the `Touchables` within the header (like the Follow button in your gif) were not pressable, because all touches events were captured by the ScrollView.

Then I thought that there might be 2 Gesture Handler : 1 `PanGestureHandler` which wraps all the screen, and another ScrollView which holds the content (not absolutely positioned). I capture events in `PanGestureHandler` to move all the content (up or down) so it's basically the same effect. But I still can't touch buttons inside my `PanGestureHandler` , so I'm thinking maybe I'm not in the right direction.

If you can help me with this that would be very great !

**Comment by haibert** [comment]
Guys I was able to find the solution from Catalin Mirons patrion which is only 5 bucks a month. DM him on Twitter and he will send you the link to it. It's actually done much in a much more simpler way than we think.

https://patreon.com/catalinmiron

**Comment by ChrisYohann** [comment]
> Guys I was able to find the solution from Catalin Mirons patrion which is only 5 bucks a month. DM him on Twitter and he will send you the link to it. It's actually done in a much more simpler way than we think.
> 
> https://patreon.com/catalinmiron

Hi @haibert, I subscribed to his channel, could you please which post is it ? I tried with the "sticky" keyword but I'm not sure that's relevant. Thanks !
