### ISSUE TITLE
uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by mahipalsingh7** [kmagiera/react-native-gesture-handler#509]
`/Users/mini2018/Projects/ReactNative/NAME_Project/XXXX/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
Some input files use unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.`

**Comment by osdnk** [comment]
Duplicated of https://github.com/kmagiera/react-native-gesture-handler/issues/489

**Comment by FibreFoX** [comment]
Maybe this should be mentioned somewhere inside the documentation, as this is a know thing?!

**Comment by osdnk** [comment]
But why? Is it an error?

**Comment by FibreFoX** [comment]
Some companies do have restrictions as part of approval procedures 😄 it makes it more easy to discuss this with dev-leads when the used library has it written somewhere. And it is confusing devs, because it might look like something that will break in near future (even if it isn't).

So it is just for clarification ;) and making it never end up in this issue-tracker again.

**Comment by osdnk** [comment]
Would you like us to explicitly say in docs: using this lib cause given warning? If yes, add PR please.

**Comment by vikramkh** [comment]
+1 I am having this issue as well

**Comment by TheMechanical** [comment]
+ I am have same problem

**Comment by baselbj** [comment]
same issue

**Comment by FibreFoX** [comment]
Instead of "same here", please use the appropiate feature .... and give the issue itself a thumb up, or reopen this as a new issue (I hate that "same here" spam)...

**Comment by juan-dalmasso-lrn** [comment]
```
react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java:
uses or overrides a deprecated API.
```
Same when trying to compile a react-native app

```
"react-native": "0.60.5",
"react-native-gesture-handler": "^1.4.1"
```

**Comment by xxczaki** [comment]
@juan-dalmasso-lrn @baselbj @vikramkh @FibreFoX @mahipalsingh7 and everyone else had who encountered this issue

Try downgrading the `react-native-gesture-handler` package to `~1.3.0`. It worked for me ;)

---

Also, a small note to @osdnk:

If you want to close an issue, because you think it is a duplicate of another, first check whether the other issue is actually closed i.e. it has a working fix, upvoted by others or a good, succinct answer. You seem not to be doing that.

**Comment by Charlicus** [comment]
I had the same issue after upgrading Gradle (to v3.5.3) in Android Studio after having installed the modules from react-navigation. (react-native 0.61.5)

This procedure worked for me:
-> Unload installed modules in android studio (from project files view)
-> Sync project ( it will reinstall the modules)
-> Run the app

**Comment by krszwsk** [comment]
For anyone else still facing this issue (after upgrading to 0.60+), **make sure you removed react-native-gesture-handler from settings.gradle.**

**Comment by viswaravi** [comment]
I had the same Issue. But adding this to app/build.gradle solved.
```
dependencies:{
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
}
```
