### ISSUE TITLE
Crashing on android with an illegalArgumentException 

### ISSUE THREAD

**Issue by fxfactorial** [kmagiera/react-native-gesture-handler#54]
Howdy, 

cross posting from this issue:

https://forums.expo.io/t/debugging-android-native-error/4792/13

**Comment by kmagiera** [comment]
@fxfactorial I'm afraid this issue is unrelated to gesture handler library. Here is why I think so:

Gesture handler library within Expo can work in "initialized" or "disabled" mode. It switches automatically "initialized" mode whenever you app uses some of the features provided by the library. Even though @RyszardRzepa mentioned he uses react-native-tab-view that depends on react-native-gesture-handler it doesn't mean the library is actually being used in this app (in fact that change landed in tab-view just a few days ago and is not yet part of any release – see [package.json](https://github.com/react-native-community/react-native-tab-view/blob/v0.0.70/package.json) from the latest release of tab-view library @0.0.70). 

From the stacktrace I can tell the library has not been "initialized". Here is the piece of code from `RNGestureHandlerEnabledRootView.java` included in Expo SDK 22
![image](https://user-images.githubusercontent.com/726445/32834165-d9d68e0c-ca01-11e7-8c2c-199686595cc2.png)

As you can see on the stacktrace line `:73` is called when `mOrchestrator == null` which means that the library is not being initialized. In that mode the rootview just proxies all the methods to superclass, which means that gesture handler library have no impact on the app.

**Comment by fxfactorial** [comment]
Thanks for such a detailed answer!
