### ISSUE TITLE
onMoveShouldSetPanResponder for PanGestureHandler?

### ISSUE THREAD

**Issue by scottmas** [kmagiera/react-native-gesture-handler#66]
I'm running into a situation PanGestureHandler is being set too soon. E.g. the PanHandler start event fires AFTER the touch has been handled by a long press. 

With a vanilla PanHandler, I would just leave `onStartShouldSetPanResponder` undefined and instead set `onMoveShouldSetPanResponder: () => true`. But there doesn't appear to be any way to do the equivalent with PanGestureHandler. Any insight?

**Comment by scottmas** [comment]
Actually, it's just a tricky question. Not specific to your library.

**Comment by kmagiera** [comment]
With gesture handler library you rely on declarative way of defining interactions between handlers. By default two handlers cannot "activate", so if that's what you're seeing it is a bug we should get reported.

So in theory you should have both long press and pan nested and only one should execute (long press if you haven't move your finger far enough and pan when you do). Would be great if you could provide simple app for this case and describe what exactly you're trying to achieve. Maybe you use long press touchable from RN (for that to work properly you should use LongPressHandler from RNGH lib). Also not sure what you are referring to as "start event". If you mean that onHandlerState gets triggered for PanHandler that's actually correct, in case when you have Pan and Long press nested they should both go into BEGAN state first then one should go to ACTIVE state and the other should change to CANCELLED (they should never both change to ACTIVE at the same time unless you use `simultaniousHandlers` prop)

You may try playing with `minDist` property of PanHandler to workaround if this turns out to be an issue. This property will allow you to set distance threshold for pan handler before it activates.
