### ISSUE TITLE
Upgrading to 1.4.0 is breaking android build (multidex 64k)

### ISSUE THREAD

**Issue by eahrold** [kmagiera/react-native-gesture-handler#736]
The changes in the 1.4.0 caused build to break on Android (RN 0.60.5 specifically)

Configuring the app with multidex enabled solved the issue
https://developer.android.com/studio/build/multidex#mdex-gradle

But it may make sense to call out the potential need in the getting started docs.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForRelease'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by radko93** [comment]
I guess it's related to your app crossing 64K limit, not to rn gesture handler itself.

**Comment by hu-qi** [comment]
I just added it to the **build. gradle** file
```
defaultConfig{
    multiDexEnabled true
}
```

![image](https://user-images.githubusercontent.com/17986122/66799543-145d8a80-ef44-11e9-927b-275fa9e14327.png)

**Comment by SaeedZhiany** [comment]
The problem is not rised by RNGH itself, but by using many RN libraries that having native modules.

Multidex Android apps have some side effects which make it not the best option  we can take (loading secondary dexes runtime might bring some latency in low-end devices)

Before enabling multidex config, we can try to using code and resource shrinking which need each RN dependency module define its proguard rule to help better shrinking.

@oblador, it would be great to define necessary proguard rules in the Android folder to help users to enabling code shrinking.
