### ISSUE TITLE
On 1.4.1 version there is black background when drawer is opened

### ISSUE THREAD

**Issue by beqramo** [kmagiera/react-native-gesture-handler#741]
I used 1.3.0 version of this lib and then I update I encountered this bug, I don't know maybe this is a react navigation bug but the reason  was this library. I hope you will find out. Thanks

**Comment by jsaraiva** [comment]
Same here.
At first I thought it could be because of me being color-blind for those tones, but the existence of other reports (and other users!) said otherwise.

**Comment by jsaraiva** [comment]
https://github.com/react-navigation/react-navigation/issues/6208#issuecomment-524091241

It's due to a mismatch between the API used by react-navigation and recent changes to react-native-gesture-handler.
The fix mentioned above (passing overlayColor: 'rgba(0, 0, 0, 0.7)' to createDrawerNavigator) works for me.
