### ISSUE TITLE
Use PureComponent instead of Component

### ISSUE THREAD

**Issue by brunolemos** [kmagiera/react-native-gesture-handler#76]
I'm using https://github.com/maicki/why-did-you-update to avoid unnecessary rerenders and it's complaining about Swipeable:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/619186/33920580-ea16a25c-dfa5-11e7-8dda-1a5af5a9dc79.png">

**Comment by kmagiera** [comment]
Now finding @brunolemos do you mind sending a PR for this change?

**Comment by kmagiera** [comment]
Sorry for the confustion, but now when I think about it it seems undesirable in most of the cases to use PureComponent as we don't have guarantee that children users put are also going to be pure.

In your case when all your components under Swipeable are pure you can make the main component that renders Swipeable pure which should help you avoid unnecessary re-renders.

**Comment by brunolemos** [comment]
@kmagiera But maybe it's a better default? https://twitter.com/sebmarkbage/status/940484973953294337

**Comment by kmagiera** [comment]
I think the additional renders that are caught by the tool you are using are due to the fact that Swipeable uses onLayout callback and sets state from it. OnLayout is used in order for us to calculate thresholds for when the row should animated to open vs closed state. We use that state to update animated values. We measure three things:
 1) width of the whole row
 2) width of the actions that can be revealed while swiping right
 3) width of the actions that can be revealed while swiping left

I wonder if maybe one of these onLayout events gets triggered more than once with the same value which leads to that extra re-render. Therefore I'm fine with changing Swipeable to extend PureComponent.

As for using PureComponent elsewhere I am still hesitant on accepting that PR. Seems like there is no consensus around that even in react team and I don't want to escalate confusion around that topic by forcing this new approach. Unless core react-native migrates all the components to  PureComponent I prefer to keep it the way it is.

**Comment by brunolemos** [comment]
I created #83 but I think PureComponent has no utility when the component has a`children` because jsx always creates a new ref on render, so I closed it.
