### ISSUE TITLE
[PanGestureHandler] using 2 PanGestureHandler

### ISSUE THREAD

**Issue by pvthuyen** [kmagiera/react-native-gesture-handler#93]
Can I let a PanGestureHandler respond to gestures starting from 2 edges of the screen and another respond to gestures starting from the middle part of the screen?

**Comment by kmagiera** [comment]
Hey @pvthuyen ! Thanks for reaching out!

You can use as many panhandler as you'd like. In your particular case I recommend that you nest three handlers one under another. Then use `hitSlop` property with the ones you'd like to activate at the edge to limit the area at which they can get activated. You can check out the code for Drawer component to see an example of how can you use PanHandler with hitSlop so that it activates at the edge

**Comment by pvthuyen** [comment]
Hi @kmagiera, I tried hitSlop and it works perfectly on iOS but it doesn't on Android.

**Comment by kmagiera** [comment]
Have you got a chance to look on how Drawer is implemeted. It uses hitSlop and works on both Android and iOS. 

If you are still facing some issues can you please elaborate a bit more what you mean by saying "hitSlop" does not work and what exactly you tried.

**Comment by osdnk** [comment]
Decided to close this issue. It seems to be inactive. 
If you still have a problem, please give us more details and reopen this thread.
