### ISSUE TITLE
How to set min/max range to cancel gesture

### ISSUE THREAD

**Issue by zachgibson** [kmagiera/react-native-gesture-handler#97]
Is there a prop to stop or cancel the gesture once it hits a minimum or maximum value?

I’m working on a Slider component and I need to stop not only the UI from moving but the value of either translationX or absoluteX. For the Animated UI I found I could set a clamped range by using `interpolate`, but the value would still increase or decrease once the max or min was surpassed.

**Comment by kmagiera** [comment]
Hey @zachgibson 

As you mentioned the best way is to use Animated.interpolate with clamp. Not sure why you'd need the actual translationX to stay within the specified range, you can always use the interpolated value, right?

If you'd like to stop gesture handler at certain moment (e.g. if you reached the edge or sth) there isn't a good way now, you have two options:
 1) Make it so that the area you allow interaction in is fully covered by some View, then add PanHandler to that view and set `shouldCancelWhenOutside={true}` – this will make PanHandler cancel when you move your finger out of the view area
 2) You can change `enabled={false}` property of gesture handler at certain moment (e.g. by setting component state or sth). This will cancel gesture handler if it's currently active. Then you can immediately flip it to `enabled={true}` so that user can interact with it again.

I'd love to learn a bit more about your usecase if you could share some more details.

**Comment by zachgibson** [comment]
Hey thanks @kmagiera! Number 2 is exactly what I need, I can disable Pan with setState, then use setState callback to turn it back on. I can also handle clamping my Slider value by manually setting the min and max values via setState. This is a `Text` component that I render this value in and I want it to render a range like 0–100 instead of -∞–∞.

I’m attempting to re-create [this Dribbble shot](https://dribbble.com/shots/3868232-ios-Fluid-Slider-ui-ux). Getting closer, but I’m not sure if it’s impossible to change my text value without missing frames considering the async nature of React.

**Comment by kmagiera** [comment]
So no 2 is def not an ideal solution, it would perhaps make sense to also add an imperative `cancel()` method you could call on a component ref. But as this issue was support related I'm going to close it. Feel free to open a new feature request if you'd like to use it the way I described.

**Comment by zachgibson** [comment]
Yeah I ended up using Animated to clamp extrapolation, and some logic to stop setting my text state value to create a min/max range. This worked with the exception that the slider handle width had to be accounted for in the interpolate range and this caused a delay in movement if the handle was at the very beginning or end of the slider. [Here’s a video](https://twitter.com/zacharykeith_/status/951463397358493697) of the demo, turned out pretty cool.

**Comment by kmagiera** [comment]
Sweet. Watched the video – nicely done!

**Comment by zachgibson** [comment]
Thanks man! Really appreciate your work here, it’s super empowering. Helps me buy into React Native even more.

**Comment by euroclydon37** [comment]
Having a `cancel()` method would fix my problems. I'm implementing a bottom sheet with a nested `ScrollView`. It would be awesome to be able to have the `ScrollView` `waitFor` a `PanGestureHandler` that animates the sheet up to a max height. Then, as the gesture continues, it would be nice to have `PanGestureHandler` cancel itself and allow the `ScrollView` to pick up where it left off.

The end result would be one fluid gesture that animated the sheet up and then scrolls the content in the `ScrollView`.
